### PR TITLE
Update URLs in README to include region ID

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/Ecosystem-Infra/ecosystem-infra-rotation/issues/53.

### CODE REVIEW

**Comment by foolip** [comment]
I think I might be mistaken in https://github.com/Ecosystem-Infra/ecosystem-infra-rotation/issues/53. https://ecosystem-infra-rotation.appspot.com/ now also doesn't have the P2 section. When I filed the issue, I reloaded it furiously with caching disabled and it was still there...

Maybe there's a delay in updating the legacy region-less URLs?

**Comment by foolip** [comment]
If this is merged, then the final URL to update is in the repo description itself, which isn't under source control.

**Comment by Hexcles** [comment]
Yeah I think you misunderstood @stephenmcgruer 's comment. We don't need the region ID in URLs. ecosystem-infra-rotation-appspot.com will keep working and always be the latest version regardless of the output of deployment.

They are not exactly the same though. There's a routing going on https://cloud.google.com/appengine/docs/standard/python3/how-requests-are-routed#urls Besides, there's different cache control because they are two different domains.

**Comment by foolip** [comment]
I must have been seeing some kind of propagation delay, then. :)

**Pull request closed without merging**
