### PR TITLE
Remove import/export monitoring

### PR DESCRIPTION
**Pull request by foolip**
These bots are no longer the responsibility of the Interop Tooling team.
Export PRs getting stuck is still our responsibility, however.

That that what remains could now be a static web app, but leave
everything as-is, as what remains will likely be folded into some other
rotation anyway and this tool discontinued.

### CODE REVIEW

**Comment by foolip** [comment]
@WeizhongX can you check if there's anything in the import.md or export.md that I'm removing that should be copied over to some other place? There are some tips in there that I think are still useful.

**Comment by WeizhongX** [comment]
After this, we will not be able to see the wpt-importer/exporter status from https://ecosystem-infra-rotation.appspot.com/?

**Comment by past** [comment]
That would be correct @WeizhongX. Is this something that your team still needs or do you have other monitoring processes in place?

**Comment by WeizhongX** [comment]
We don't have other monitoring processes as of now. So let's keep this running for a while, and allow me some time to set that up.

I guess I will just copy everything and remove the part we don't need from engprod.

**Comment by foolip** [comment]
I was assuming that there is already some system for monitoring certain build bots, something superior to my scraping script :)

If there isn't, then forking this tool and deleting the unneeded parts sounds like a good approach.

We can leave it in the tool until there's a replacement, no urgency on removing it.

**Comment by foolip** [comment]
@WeizhongX is there a monitoring process for this yet? I noticed again because of https://github.com/Ecosystem-Infra/ecosystem-infra-rotation/pull/67 which would conflict with this.

**Comment by WeizhongX** [comment]
I did not work that. Maybe I can work on #67 as a compensate? But I do not understand why the two are related.

**Pull request closed without merging**
